---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PrintUtils
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: 0
  Getopt::CommandLineExports: 0
  HTML::Tabulate: 0
  Test::More: 0
  Test::Output: 0
  Time::HiRes: 0
  XML::Simple: 0
version: 0.12
