---
abstract: 'A Collection of Pretty Print routines like Data::Dumper'
author:
  - 'q{Robert Haxton <robert.haxton@gmail.com>}'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-PrintUtils
provides:
  Data::PrintUtils:
    file: lib/Data/PrintUtils.pm
    version: 0.11
requires:
  Data::Dumper: 0
  Getopt::CommandLineExports: 0
  HTML::Tabulate: 0
  Test::More: 0
  Time::HiRes: 0
  XML::Simple: 0
version: 0.11
